# fly.toml app configuration file generated for rosin-dev on 2023-10-05T14:37:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rosin-dev"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[build]

[env]
  APP_ENV = "live"
  DATABASE_URL = "file:/data/sqlite.db"
  NODE_ENV = "production"
  PORT = "3000"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
